spring.application.name=management
spring.datasource.url=jdbc:postgresql://localhost:5432/systemlibary
spring.datasource.username=postgres
spring.datasource.password=${DB_Password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret = ${jwtSecret}
jwt.expiration = 86000000000
jwt.cookie.name = ${jwtCookieName}
logging.level.org.springframework.security=TRACE
admin.password=${adminPassword}
admin.email=${adminEmail}